name: empire_env
channels:
  - conda-forge
  - defaults
dependencies:
  - cloudpickle>=1.0.0
  - openpyxl>=3.0.0
  - pandas>=1.2
  - pyomo>=6.0
  - python>=3.7
  - pyyaml>=5.1
  - glpk>=4.65
  - python==3.11
  - scipy
  - scikit-learn
  
  # For the streamlit app
  - streamlit
  - plotly

  # Docs
  - furo 
  - sphinx
  
  - pip
  - pip:
      - -e . # Install empire as pip package in editable mode
      - streamlit-authenticator