# This is an OpenEMPIRE configuration file used for test runs.
# To be used with the execution script run.py

use_temporary_directory: True
temporary_directory: './'    
forecast_horizon_year: 2030
number_of_scenarios: 2      
length_of_regular_season: 24
discount_rate: 0.05
wacc: 0.05
optimization_solver: "Gurobi"
use_scenario_generation: True
use_fixed_sample: False
use_emission_cap: False
print_in_iamc_format: True
write_in_lp_format: False
serialize_instance: False
north_sea: False
